services: &default-services
  gem: &base
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle

  test:
    <<: *base
    command: rake spec

  lint:
    <<: *base
    command: rake rubocop

  deploy:
    <<: *base
    command: ./bin/actions-deploy-gem
    environment:
      GH_TOKEN: $GH_TOKEN

volumes:
  bundle:
